#!/usr/bin/env bash

npm i
npx "@bookshop/generate"
echo "Generating site with Rosey"
npx rosey generate --source public
echo "Generated a base.json from the built site"
echo "Generating locales from base.json"
node utils/generateLocales.js
echo "Generated locales"

if [[ $TRANSLATE == "true" ]];
then
  echo "Translating site with Rosey"
  # We only want this to run on our production site, as it can interfere with CloudCannon CMS's visual editor
  # There's a little bit of shuffling around here to ensure the translated site ends up where CloudCannon picks up your site
  mv ./public ./untranslated_site                  
  npx rosey@latest build --source untranslated_site --dest public
fi